edgedbpkg/edgedb/__init__.py
integration/actions/describe-artifact/src/main.ts
integration/linux/test-systemd/centos-7/Dockerfile
integration/linux/test-systemd/centos-8/Dockerfile
integration/linux/test-systemd/debian-buster/Dockerfile
integration/linux/test-systemd/debian-stretch/Dockerfile
integration/linux/test-systemd/entrypoint-centos.sh
integration/linux/test-systemd/entrypoint-debian.sh
integration/linux/test-systemd/fedora-29/Dockerfile
integration/linux/test-systemd/ubuntu-bionic/Dockerfile
integration/linux/test-systemd/ubuntu-focal/Dockerfile
integration/linux/test-systemd/ubuntu-xenial/Dockerfile
integration/linux/test/centos-7/Dockerfile
integration/linux/test/centos-8/Dockerfile
integration/linux/test/debian-buster/Dockerfile
integration/linux/test/debian-stretch/Dockerfile
integration/linux/test/entrypoint-centos.sh
integration/linux/test/entrypoint-debian.sh
integration/linux/test/ubuntu-bionic/Dockerfile
integration/linux/test/ubuntu-focal/Dockerfile
integration/linux/test/ubuntu-xenial/Dockerfile
integration/macos/test.sh
server/containers/aptrepo/makeindex.py
server/containers/genrepo/findold.py
server/containers/genrepo/makeindex.py
server/containers/genrepo/processincoming.sh
server/containers/rpmrepo/makeindex.py

Changes the version slot from, say, `edgedb-server-1-alpha6` to `edgedb-server-1-alpha6-dev5034`. The dev part is taken directly from the setuptools-scm version scheme, which is the number of commits on the branch. This should make the dev builds effectively monotonic, easy to parse to the human eye, and useful to say, for example: "yeah this EdgeQL syntax is only available since dev6123".

Make dev builds (like nightlies) their own slots

---

edgedbpkg/edgedbcli/install.list
integration/win/build.sh
integration/win/publish.sh

This treats Windows as a Unix-ish target that has all the necessary GNU
tools, Python, Git, Rust etc.
Closes: #5

Rudimentary Windows support

---

README.rst

We no longer support HTTP-based repository dispatch. Now we're doing it straight from the UI.

Describe how nightlies and releases are triggered

---

server/containers/genrepo/Dockerfile
server/containers/genrepo/config/incron/incron.allow
server/containers/genrepo/config/incron/incrontab
server/containers/genrepo/entrypoint.sh
server/containers/genrepo/process_incoming.py
server/containers/genrepo/visor.py

This also puts inoticoming in place of incrond which was unsafe (its use of `system()` allows for an attacker to execute arbitrary commands by using malicious filenames) and made it impossible to see any logs on AWS CloudWatch. The current approach logs with no buffering, leading to an "almost realtime" stream on CloudWatch.

Replace bash-based daemon servicing with a mini Python supervisor

---

server/containers/aptrepo/entrypoint.sh
server/containers/genrepo/Dockerfile
server/containers/genrepo/entrypoint.sh
server/containers/rpmrepo/entrypoint.sh

When specifying a group for gosu, other applicable groups for the user are no
longer checked. This broke genrepo but was invalid in all three uploaders.

Don't specify group for gosu

---

server/containers/genrepo/process_incoming.py

Currently, edgedb-cli is erroneously linked as "edgedb-cliNone_latest"

Fix unslotted latest symlink in genrepo

---

server/containers/genrepo/process_incoming.py

The index update script uses object key prefix, which picks up stable
_and_ nightly artifacts.  Add a check to filter nightlies out properly.
Also, stop including subdist in the "architecture" field in the index,
it's not supposed to be there.

genrepo: Prevent nightlies from leaking into stable index

---

server/containers/genrepo/process_incoming.py

The installref for genrepo artifacts should contain the leading slash.
Fixes: edgedb/edgedb-cli#209

Fix installref regression in genrepo

---

integration/linux/upload/entrypoint-linux.sh
integration/linux/upload/linux-x86_64/Dockerfile

Because genrepo runs as a vm under systemd, the sshd listens on the normal port.  2222 was used because: docker

non-dockerized genrepo sshd listens on port 22

---

server/process_incoming.py
server/pyproject.toml

`inoticoming` will happily call `process_incoming` concurrently, so make
sure we're properly locking the repos to avoid corruption.

Make sure process_incoming is serialized

---

server/process_incoming.py
server/pyproject.toml

`apt_pkg` is only available as a system package on Debian, which makes
`process_incoming` not very portable, including preventing use of
virtualenvs.  It's not really needed, we can use `semver` sorting
instead in the remaining `apt_pkg` call site.

Remove apt_pkg dependency

---

server/process_incoming.py
server/pyproject.toml

This reverts commit 02e4686c3a3cd8a65c93050a0a255c4740e2692b and replaces it with the use of portable `python-debian`.

Revert "Remove apt_pkg dependency (#65)"

---

Makefile
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/debian-bookworm/Dockerfile
integration/linux/build/debian-bullseye/Dockerfile
integration/linux/build/debian-buster/Dockerfile
integration/linux/build/entrypoint.sh
integration/linux/build/fedora-29/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile
integration/linux/build/linuxmusl-aarch64/Dockerfile
integration/linux/build/linuxmusl-x86_64/Dockerfile
integration/linux/build/rockylinux-9/Dockerfile
integration/linux/build/ubuntu-bionic/Dockerfile
integration/linux/build/ubuntu-focal/Dockerfile
integration/linux/build/ubuntu-hirsute/Dockerfile
integration/linux/build/ubuntu-jammy/Dockerfile
server/process_incoming.py

The incoming package may now declare which bucket it wants to go in
using an identifier, and a mapping from bucket identifiers to actual
bucket names can be specified in the new `[common.buckets]` config key.

Allow configuring multiple buckets for `process_incoming.py`

---

integration/linux/build/Dockerfile-centos.template
integration/linux/build/Dockerfile-linux.template
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile

rpm on centos 7 calls fcntl on every FD up to the max in order to set CLOEXEC, and the maximum number of open FDs in docker on our runners was 2**30 - 8 == 1073741816.
(See https://github.com/rpm-software-management/rpm/pull/444).
The result was that builds using centos 7 were taking almost 4 hours instead of a couple minutes.
(We upgraded the version of the thing we were using to run the jobs on Nov 6, and I suspect that caused the ulimit to change from about a million (wasteful, but not a diaster) to about a billion (much worse).)
ulimit can't be configured in a Dockerfile, and there doesn't seem to be a way to pass argument to `docker build` if you are using the default github action, so just call ulimit before the big yum install.
There might be a way to configure it on our infra …

Set ulimit -n to 1024 on centos targets

---

edgedbpkg/edgedb/__init__.py

Pass `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` when building
`cryptography` so that its `openssl-sys` crate dependency is happy.

Configure `cryptography` more thoroughly

---

edgedbpkg/edgedb/__init__.py

Build EdgeDB 5 with Python 3.12

---

integration/macos/test.sh

The idea here is that it will let us run a more trimmed down list of
tests for macos on x86, where the tests are shockingly slow.

Allow actions to pass in a specific list of tests to run on macos

---

integration/linux/build/Dockerfile-centos.template
integration/linux/build/Dockerfile-linux.template
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile

I did at least partially test it this time.

Actually fix it?

---

integration/linux/build/Dockerfile-linux.template
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile

All of the conditional logic is totally uneeded, I realize now, since
it is always being run on centos 7.
The issue on aarch64 is that the baseurl in the SCLo sources doesn't
work on arm, since it has `/centos` and not `/altarch`, so we need to
work that out.
Also, switch to the archive.kernel.org mirror.

Fix on aarch64 and simplify a bit

---

edgedbpkg/edgedb/no_install.list

edgedb-server build was broken since I've added `edgedb-ls.py` to `project.scripts` in `pyproject.toml` of the main repo.
This PR just adds these files to no_install list of edgedb-server.

Fix edgedb-server after edgedb-ls was added

---

edgedbpkg/edgedb/__init__.py

Setuptools 70.2.0 (and more recently 72.0.0) have various breakage, so
pin to `<70.2.0` for now.

Pin setuptools build dep to <70.2.0

---

edgedbpkg/postgresql/__init__.py

There's no reason for us to clone the entire Postgres git repo,
especially given that Poetry is using dulwich which is extremely
inefficient about cloning large repos.

postgresql: Use a tarball source instead of git

---

edgedbpkg/postgresql/patches/postgresql-edgedb__gate_statement_log-14.patch
edgedbpkg/postgresql/patches/postgresql-edgedb__gate_statement_log-15.patch
edgedbpkg/postgresql/patches/postgresql-edgedb__gate_statement_log-16.patch

This patch drops STATEMENT longer than 128 bytes in the log of serialization errors.

Gate long STATEMENT log in SERIALIZATION error

---

edgedbpkg/edgedb/__init__.py

This is newly required by the Rust extension: https://github.com/edgedb/edgedb/pull/7659
[Sample run](https://github.com/edgedb/edgedb/actions/runs/10744289499)

Add OpenSSL as dependency of EdgeDB 6

---

edgedbpkg/edgedb/__init__.py

Ubuntu bionic also uses bundled OpenSSL, the relative search path seems to be different. Without this PR, we get [this error](https://github.com/edgedb/edgedb/actions/runs/10747507342/job/29810025945#step:3:4161):
```
invalid relative_to argument: buildroot
at /usr/local/lib/python3.9/site-packages/metapkg/targets/deb/build.py:78 in get_path
74│             return pathlib.Path("..") / ".." / path
75│         elif relative_to == "fsroot":
76│             return (self.get_source_abspath() / path).resolve()
77│         else:
→  78│             raise ValueError(f"invalid relative_to argument: {relative_to}")
79│ 
80│     def get_spec_root(
81│         self, *, relative_to: targets.Location = "sourceroot"
82│     ) -> pathlib.Path:
```
[Sample run with this …

Fix Ubuntu bionic (bundled OpenSSL)

---

edgedbpkg/edgedb/__init__.py
edgedbpkg/edgedb/install.list

Add edgedb-load-ext.py to the install.list

---

integration/linux/build/Dockerfile-centos.template
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile

Fixes https://github.com/edgedb/edgedb/actions/runs/11226917010/job/31208267706#step:2:44

Fix centos:8: yum-plugin-fastestmirror is not installed by default

---

edgedbpkg/postgresql/patches/postgresql-edgedb__wsl1-17.patch

Add the missing "common/string.h" include

postgres: Fix WSL1 detection patch for Postgres 17

---

edgedbpkg/edgedb/__init__.py
edgedbpkg/pgext/edb_stat_statements/__init__.py
edgedbpkg/pgext/edb_stat_statements/install.list

[Sample run](https://github.com/edgedb/edgedb/actions/runs/11979532779)

Build edb_stat_statements

---

integration/linux/test/linuxmusl-aarch64/Dockerfile

It keeps flaking due to a known flake fixed in 6.x that hasn't been
backported and I just want to get the stupid release out.

Disable linux musl aarch64 test

---

integration/linux/test/linuxmusl-aarch64/Dockerfile

This reverts commit f270bde7653724bb8787c5f03c96d1940ef7cb4d.

Revert "Disable linux musl aarch64 test (#125)"

---

edgedbpkg/edgedb_ls/__init__.py
edgedbpkg/edgedb_ls/install.list

- **edgedb-ls: Add build dependency on libprotobuf-c (for libpg_query stuff)**
- **edgedb-ls: fix missing edgedb-ls in install.list**

edgedb-ls: fix install.list and protobuf dependency

---

edgedbpkg/pyentrypoint/rust/Cargo.toml
edgedbpkg/pyentrypoint/rust/src/main.rs

MacOS seems to launch symlinks with argv[0] pointing at the symlink rather than the final resolved file.

Follow symlinks on MacOS

---

edgedbpkg/edgedb/IDENTIFIER-SLOT.plist.in
edgedbpkg/edgedb/IDENTIFIER-SLOT.service.in
edgedbpkg/edgedb/__init__.py

This is a bit of a SNAFU, because the service units are broken on fresh
systems, and on systems where EdgeDB 5.x and earlier was installed they
would work, but will initialize the data in the wrong spot
(`/var/lib/edgedb`) and owned by the wrong user (`edgedb`).  This fixes
the units and adds a check that errors out if the wrong data directory
is detected, so people who have successfully installed Gel 6.0/6.1 would
be informed to move and `chown` the data directory when upgrading to 6.2
and later.

Fix unrenamed bits in system units shipped in native packages

---

server/process_incoming.py

S3 has a hard limit of 50 redirect rules and we overflow those with the
combination of channels, platforms, compression formats and the rebrand.
This buys us more breathing room by only publishing the redirect to an
uncompressed binary, which is what we use anyway.

Only create bucket redirects for uncompressed versions

---

edgedbpkg/edgedb/__init__.py
integration/linux/build/_bootstrap/python.sh
integration/linux/build/amazonlinux-2023/Dockerfile
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/debian-bookworm/Dockerfile
integration/linux/build/debian-bullseye/Dockerfile
integration/linux/build/debian-buster/Dockerfile
integration/linux/build/entrypoint.sh
integration/linux/build/fedora-40/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile
integration/linux/build/linuxmusl-aarch64/Dockerfile
integration/linux/build/linuxmusl-x86_64/Dockerfile
integration/linux/build/rockylinux-9/Dockerfile
integration/linux/build/ubuntu-bionic/Dockerfile
integration/linux/build/ubuntu-focal/Dockerfile
integration/linux/build/ubuntu-hirsute/Dockerfile
integration/linux/build/ubuntu-jammy/Dockerfile
integration/linux/build/ubuntu-noble/Dockerfile
integration/linux/build/update.sh

It was originally pinned by #101.
I'm keeping a pin on a major verson, because upgrading major
version automatically might cause breakage in the future.
I need this update, because calver has published a broken
version, followed by a fix that bumps required setuptools.
Which means we cannot use the fix unless we update setuptools.

Update setuptools to 77 for GelNoPostgres

---

edgedbpkg/postgresql/install.list

`pg_waldump` is required by `pg_verifybackup`

Add pg_waldump to postgres server package

---

integration/win/build.sh

The error was:
https://github.com/geldata/gel-cli/actions/runs/14844894394/job/41680123790#step:6:77
```
+ -m venv .venv
edgedb-pkg/integration/win/build.sh: line 72: -m: command not found
```

Fix missing $PYTHON command

---

integration/win/build.sh

The virtualenv on Windows uses `Scripts` instead of `bin`
Refs #160, aa03e30e21d70f2364355a7ea2a09873df61c110

Fix venv path on windows

---

integration/linux/build/Dockerfile-debian.template
integration/linux/build/debian-buster/Dockerfile

It is out of support, so point it at archive.debian.org instead.
We'll want to drop it, but probably not for 6.x.
Apparently we have support for casing on the variant in our template
files... I learned a lot more about sed today trying to understand
what update.sh was doing.

Fix debian buster build
