integration/linux/build/Dockerfile-centos.template
integration/linux/build/centos-8/Dockerfile

This is needed to build openssl for cli tools

Add perl-getopt-long package to centos

---

edgedbpkg/edgedb/__init__.py

Auto-remove edgedb-common on new edgedb-server installations

---

README.rst
integration/linux/upload/debian-buster/Dockerfile
integration/linux/upload/debian-stretch/Dockerfile
integration/linux/upload/ubuntu-bionic/Dockerfile
integration/linux/upload/ubuntu-focal/Dockerfile
integration/linux/upload/ubuntu-xenial/Dockerfile
integration/win/publish.sh
server/README.rst

Also update the Windows port and expand the README a bit.

Run `make` in linux/uploads to update the changed port numbers

---

README.rst
integration/linux/upload/debian-buster/Dockerfile
integration/linux/upload/debian-stretch/Dockerfile
integration/linux/upload/ubuntu-bionic/Dockerfile
integration/linux/upload/ubuntu-focal/Dockerfile
integration/linux/upload/ubuntu-xenial/Dockerfile
integration/win/publish.sh
server/README.rst
server/containers/aptrepo/Dockerfile
server/containers/aptrepo/entrypoint.sh
server/containers/aptrepo/fetch_secrets.py
server/containers/aptrepo/processincoming.sh
server/containers/genrepo/entrypoint.sh

Fetches secrets from AWS SecretsManager, which includes authorized_keys, the host key, and the GPG keys for signing.

Make aptrepo work on AWS, minimal version

---

server/containers/aptrepo/Dockerfile
server/containers/aptrepo/entrypoint.sh
server/containers/aptrepo/fetch_secrets.py
server/containers/aptrepo/processincoming.sh
server/containers/aptrepo/visor.py
server/containers/genrepo/entrypoint.sh
server/containers/genrepo/fetch_secrets.py

gsutil was unable to authenticate within AWS Fargate tasks and we don't want to hand out AWS access tokens manually within AWS as it's a security risk and a big inconvenience.

Drop usage of gsutil and use `aws s3` instead

---

server/containers/rpmrepo/Dockerfile
server/containers/rpmrepo/config/incron/incron.allow
server/containers/rpmrepo/config/incron/incrontab
server/containers/rpmrepo/entrypoint.sh
server/containers/rpmrepo/fetch_secrets.py
server/containers/rpmrepo/makeindex.py
server/containers/rpmrepo/processincoming.sh
server/containers/rpmrepo/visor.py

- upgrade to Centos 8
- storage in S3
- host key, authorized_keys, and GPG keys in AWS SecretsManager
- inoticoming instead of incron
- gosu instead of sudo
- visor.py instead of bash-based daemon supervising

Move rpmrepo to AWS

---

server/containers/genrepo/process_incoming.py

Objects in `dist/` are "convenience" objects, i.e. they are a well-known
URL to the latest build in a given repo.  Since they're updated on every
build, we can't cache or CDN them properly, but we _can_ generate a
redirect from `dist/` to the corresponding object in `archive/`.
The easiest way to do redirects in S3 is to slap an
`x-amz-website-redirect-location` metadata header on an object.
Unfortunately, S3 generates a "301 Moved Permanently" response for such
objects and doesn't bother to also send a `Cache-Control` header, which
makes the redirect cacheable and useless for the purpose of a
frequently-updated pointer.
Fortunately, S3 static website hosting supports bucket-wide redirection
rules, which _do_ allow control over the response code, and so we use
that.  There is a limit of …

genrepo: Generate a bucket-wide redirect policy from dist/ to archive/

---

integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/debian-buster/Dockerfile
integration/linux/build/debian-stretch/Dockerfile
integration/linux/build/fedora-29/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile
integration/linux/build/ubuntu-bionic/Dockerfile
integration/linux/build/ubuntu-focal/Dockerfile
integration/linux/build/ubuntu-hirsute/Dockerfile
integration/linux/build/ubuntu-xenial/Dockerfile
integration/linux/build/update.sh

The counterpart of the https://github.com/edgedb/edgedb/pull/2649
Script also updated Python and Pip versions. Let me know if I need to revert these.

Update Rust to 1.53.0

---

server/process_incoming.py

For consistent logging, make sure all output goes to stderr

Replace prints with logging and redirect subprocess output to stderr

---

integration/macos/test.sh

This reverts commit 33f24c316f5eb6d94b4d359c41b0d4d2dfcc4304.

Revert "Temporarily disable most macos test (#80)"

---

integration/macos/test.sh

This reverts commit 99d39972559b9f8b8e28fc9e34a70ca2b37f6ebf.

Revert "Temporarily disable most macos test (#82)"

---

integration/macos/test.sh

Maybe get the filename thing right this time

---

integration/macos/test.sh

... unless there are spaces in any file name.
I even tested it this time.

Actually fix the PKG_TEST_FILES thing

---

integration/linux/build/Dockerfile-centos.template
integration/linux/build/Dockerfile-linux.template
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile

Though we should probably also stop using it soon

Fix centos 7

---

integration/linux/testpublished/Dockerfile-centos.template
integration/linux/testpublished/centos-7/Dockerfile
integration/linux/testpublished/centos-8/Dockerfile

This should unbreak [CLI builds CI](https://github.com/edgedb/edgedb-cli/actions/runs/9923850810/job/27414764379)
Refs:
* https://serverfault.com/a/1161904
* https://github.com/edgedb/edgedb-pkg/commit/a675046207a7e148c2b68159070b857aa2df6e65
* https://github.com/edgedb/edgedb/pull/6864
* #97

Unbreak CentOS 7 testpublished

---

integration/linux/build/Dockerfile-centos.template
integration/linux/build/Dockerfile-debian.template
integration/linux/build/Dockerfile-fedora.template
integration/linux/build/Dockerfile-linux.template
integration/linux/build/Dockerfile-linuxmusl.template
integration/linux/build/Dockerfile-rockylinux.template
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/debian-bookworm/Dockerfile
integration/linux/build/debian-bullseye/Dockerfile
integration/linux/build/debian-buster/Dockerfile
integration/linux/build/fedora-29/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile
integration/linux/build/linuxmusl-aarch64/Dockerfile
integration/linux/build/linuxmusl-x86_64/Dockerfile
integration/linux/build/rockylinux-9/Dockerfile
integration/linux/build/ubuntu-bionic/Dockerfile
integration/linux/build/ubuntu-focal/Dockerfile
integration/linux/build/ubuntu-hirsute/Dockerfile
integration/linux/build/ubuntu-jammy/Dockerfile
integration/linux/build/ubuntu-noble/Dockerfile

[Sample run](https://github.com/edgedb/edgedb/actions/runs/10223624841)

Add cmake to Linux build images

---

integration/linux/build/Dockerfile-linux.template
integration/linux/build/linux-aarch64/Dockerfile

Refs https://github.com/edgedb/edgedb-pkg/pull/105#issuecomment-2284951490

Use GCC 10 on aarch64 CentOS 7

---

integration/linux/build/Dockerfile-linux.template
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile

This seems to be a regression from #111
[Sample run](https://github.com/edgedb/edgedb/actions/runs/11240206126)

Fix linux-aarch64 build

---

edgedbpkg/edgedb_ext/vectorstore/__init__.py
edgedbpkg/edgedb_ext/vectorstore/install.list
edgedbpkg/edgedb_ext/vectorstore/no_install.list

Copy package info over from postgis.

Register vectorstore package

---

integration/linux/build/.gitattributes
integration/linux/build/_bootstrap/_helpers.sh
integration/linux/build/_bootstrap/cmake.sh
integration/linux/build/_bootstrap/git.sh
integration/linux/build/_bootstrap/gzip.sh
integration/linux/build/_bootstrap/node.sh
integration/linux/build/_bootstrap/openssl.sh
integration/linux/build/_bootstrap/python.sh
integration/linux/build/_bootstrap/tar.sh
integration/linux/build/_bootstrap/yarn.sh
integration/linux/build/amazonlinux-2023/Dockerfile
integration/linux/build/centos-7/Dockerfile
integration/linux/build/centos-8/Dockerfile
integration/linux/build/debian-bookworm/Dockerfile
integration/linux/build/debian-bullseye/Dockerfile
integration/linux/build/debian-buster/Dockerfile
integration/linux/build/fedora-40/Dockerfile
integration/linux/build/linux-aarch64/Dockerfile
integration/linux/build/linux-x86_64/Dockerfile
integration/linux/build/linuxmusl-aarch64/Dockerfile
integration/linux/build/linuxmusl-x86_64/Dockerfile
integration/linux/build/rockylinux-9/Dockerfile
integration/linux/build/ubuntu-bionic/Dockerfile
integration/linux/build/ubuntu-focal/Dockerfile
integration/linux/build/ubuntu-hirsute/Dockerfile
integration/linux/build/ubuntu-jammy/Dockerfile
integration/linux/build/ubuntu-noble/Dockerfile

Avoid code duplication and make it more resilient by adding a couple
more keyservers.

build: Extract gpg key fetching into a helpers

---

edgedbpkg/edgedb_ext/postgis/__init__.py

We do need to fix this, though.

Pin postgis to 3.5.1

---

integration/linux/test/entrypoint-linux.sh
integration/linux/test/entrypoint-linuxmusl.sh
integration/linux/test/linux-aarch64/Dockerfile
integration/linux/test/linux-x86_64/Dockerfile
integration/linux/test/linuxmusl-aarch64/Dockerfile
integration/linux/test/linuxmusl-x86_64/Dockerfile

Nightly CLIs are returning zero bytes

Download stable CLIs for running tests

---

integration/linux/mkdockerfile.sh
integration/linux/test-systemd/Dockerfile-debian.template
integration/linux/test-systemd/debian-buster/Dockerfile
integration/linux/test/Dockerfile-debian.template
integration/linux/test/debian-buster/Dockerfile

Fix the test side for buster too

---

integration/linux/testpublished/Dockerfile-debian.template
integration/linux/testpublished/debian-buster/Dockerfile

Fix the check published side for buster
